### ISSUE TITLE
out-of-tree build is broken for ages

### ISSUE THREAD

**Issue by monsta** [mate-desktop/caja-dropbox#22]
Which in its turn breaks distcheck.

```
$ NOCONFIGURE=1 ./autogen.sh
$ mkdir build
$ cd build
$ ../configure ...
$ make
```

It will break:

```
make[2]: Leaving directory '/home/monsta/mate/caja-dropbox/build/src'
make[2]: Entering directory '/home/monsta/mate/caja-dropbox/build'
python serializeimages.py 1.12.0 /usr/share/applications < caja-dropbox.in > caja-dropbox
/bin/bash: caja-dropbox.in: No such file or directory
```

Even if you edit the top `Makefile.am` and add `$(top_srcdir)/` to the file names, the build will break anyway due to `serializeimages.py` not caring about building from any other dir.

**Comment by raveit65** [comment]
fixed by https://github.com/mate-desktop/caja-dropbox/commit/05e1e93acb86fc0e28f69acfd0cced773b140ff6 and
https://github.com/mate-desktop/caja-dropbox/commit/6d281bce63215b21ebed7542a5cc4a3669f07f1f
