### ISSUE TITLE
cherry-pick Debian patches upstream

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/caja-dropbox#25]
Hi,

the caja-dropbox Debian packages currently ships 9 patches that should be interesting for upstream.

Please investigate and cherry-pick where appropriate (patches number 1001-1009):
 https://anonscm.debian.org/cgit/pkg-mate/caja-dropbox.git/tree/debian/patches?id=9401c6ce6af864c997deffc31a69f59874e0bf3a

**Comment by sc0w** [comment]
https://salsa.debian.org/debian-mate-team/caja-dropbox/tree/master/debian/patches

**Comment by raveit65** [comment]
done
