### ISSUE TITLE
caja-dropbox 1.12 does not autostart on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/caja-dropbox#26]
#### Expected behaviour
`caja-dropbox` is autostarted after reboot and shows its icon in system tray.

#### Actual behaviour
`caja-dropbox` is not autostarted, its icon is not shown in system tray.

#### Steps to reproduce the behaviour
1. Install Ubuntu MATE 16.04.4 LTS
2. Install `caja-dropbox` package
3. Launch `caja-dropbox`, log-in to the Dropbox account, set its autostart in _Preferences_ by _Start Dropbox when system starts_
4. Reboot system

#### MATE general version
1.12.1-1

#### Package version
1.12.0-3

#### Linux Distribution
Ubuntu 16.04 LTS

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/ubuntu/+source/caja-dropbox/+bug/1604439 

#### Temporary fix
Open terminal and execute `caja-dropbox autostart y`.

**Comment by raveit65** [comment]
Is there and launcher in 
```
[rave@mother ~]$ ls -l ~/.config/autostart/
insgesamt 68
<cut>
-rw-rw-r--. 1 rave rave   262 24. Feb 08:05 dropbox.desktop
<cut>
```
This launcher should be created during installation of the proprietary software

**Comment by N0rbert** [comment]
During installation of `caja-dropbox` proprietary part was downloaded (DropBox v.43.4.50),
then it opened Firefox for authentication, after it opened Caja in `~/Dropbox` folder. Also it shown icon in notification area/tray.
Then I clicked on systemtray icon, selected *Preferences->General* and checked *Start Dropbox on system start-up* and rebooted.
After reboot I do not have Dropbox icon in tray, it does not have desktop-file in XDG autostart:

```
$ ls -l ~/.config/autostart/
ls: cannot access '/home/xenial/.config/autostart/': No such file or directory

```

and is not listed in `mate-session-properties`. Caja does not have special overlay icon on `~/Dropbox` folder.
If I run Dropbox manually again it shows *Start Dropbox on system start-up* unchecked in *Preferences*.

After having 15-minutes of googling I found solution (`caja-dropbox autostart y`):

```
xenial@xenial-vb:~$ caja-dropbox autostart y
xenial@xenial-vb:~$ ls -l ~/.config/autostart/
total 4
-rw-rw-r-- 1 xenial xenial 329 фев 24 14:20 caja-dropbox.desktop
```

Dropbox shows its icon in system-tray, Caja shows overlay icon on `~/Dropbox` folder and works correctly.

As far I can understand `caja-dropbox` is very often used and handy, moreover you have it in MATE Software Boutique (`ubuntu-mate-welcome`). Its functionality needs online sync and tray icon (or background server daemon - `dropboxd`). So it should work out the box and autostart if user asks for autostart. Newbies will be disappointed.

**Comment by raveit65** [comment]
Hmm, this is bad.
But i can't really reproduce it, because i am using fedora and here the situation is different.
At rpmfusion repo we use latest nautilus-dropbox.
caja-dropbox or nemo-dropbox are shipping only the browser part.
/usr/lib64/caja/extensions-2.0/libcaja-dropbox.so
They are depending on nautilus-dropbox and using the binary from this package.
/usr/bin/dropbox
I just tested installation again in f26 VM, and everything works well here.
After i signed in my dropbox account in webbrowser the dropbox.desktop is there, without selecting this option in dropbox icon.

But i recal that i used some patches for fedora to fix the problem before we use the nautilus dropbox binary.
I can't promise it but maybe i found a hint in older packages for fedora......

**Comment by N0rbert** [comment]
For your information - I do not know why, but `nautilus-dropbox` adds autostart launcher normally on the Ubuntu 16.04 LTS with GNOME.   

Am I understand correctly that the problem is in [`postinst`](https://anonscm.debian.org/git/pkg-mate/caja-dropbox.git/tree/debian/caja-dropbox.postinst) or somewhere else on distro-side? So is it packaging issue?

**Comment by N0rbert** [comment]
OK, thank you for your time and efforts. 

I'll test on Debian Stretch (9) too and report back.

**Comment by raveit65** [comment]
I found my old workaround to start dropbox in session.
1. a desktop file /usr/xdg/autostart/start-dropbox.desktop
```
[Desktop Entry]
Name=start-dropbox
GenericName=File Synchronizer
Comment=Sync your files across computers and to the web
Exec=start-dropbox start
OnlyShowIn=MATE;
NoDisplay=true
Terminal=false
Type=Application
Icon=caja-dropbox
StartupNotify=false
X-MATE-Bugzilla-Bugzilla=MATE
X-MATE-Bugzilla-Product=caja-dropbox
X-MATE-Bugzilla-Component=general
X-MATE-Bugzilla-Version=1.6.1
X-MATE-Autostart-Notify=true
X-MATE-AutoRestart=false
```
a script /usr/bin/start-dropbox
```
#!/bin/bash

test -r ~/.dropbox-dist/dropbox && ~/.dropbox-dist/dropbox &

exit
```

**Comment by N0rbert** [comment]
Your script needs small editing (Dropbox is installed into `/var/lib/dropbox/.dropbox-dist/dropbox-lnx.x86_64-43.4.50/dropbox`). I changed  `/usr/bin/start-dropbox` to

```
#!/bin/bash

caja-dropbox start

exit
```

Or just
```
cat > ~/.config/autostart/caja-dropbox.desktop << EOF
[Desktop Entry]
Name=Caja Dropbox
GenericName=File Synchronizer For Mate
Comment=Installs and launches proprietary Dropbox cloud software
Exec=caja-dropbox start -i
OnlyShowIn=MATE;
NoDisplay=true
Terminal=false
Type=Application
Icon=caja-dropbox
StartupNotify=false
X-MATE-Autostart-Notify=true
X-MATE-AutoRestart=false
EOF
```

But `caja-dropbox autostart y` is simpler and straightforward.

Debian 9.3 has [`caja-dropbox` 1.16](https://packages.debian.org/stretch/caja-dropbox) and [1.20](https://packages.debian.org/sid/caja-dropbox). In both Caja does not autostart, so I reported [bug 891349 to their BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891349).

**Comment by raveit65** [comment]
Well, there are several ways to fix that :)
